---
- name: deploy some servers
  apt:
    name:
      - default-mysql-server
      - tomcat
      - apache2
    state: latest
  when: inventory_hostname in groups["prez"]

- name: stop service
  service:
    name:
      - default-mysql-server
      - tomcat
      - apache2
    state: stopped
  when: inventory_hostname in groups["prez"]