- name: deploy some service
  apt:
    name:
      - "{{ serveur_http }}"
      - "{{ sereur_app }}"
      - "{{ dbserver }}"
    state: latest
  when: inventory_hostname in groups["prez"]

- name:
    services:
      - "{{ serveur_http }}"
      - "{{ sereur_app }}"
      - "{{ dbserver }}"
    state: stopped
  when: inventory_hostname in groups["prez"]
#- name:
#    apt:
#      name: upgrade
#  when: inventory_hostname in groups["prez"]
