---
- name: deploy some servers
  apt:
    name:
      - "{{ serveur_http }}"
      - "{{ sereur_app }}"
      - "{{ dbserver }}"
    state: latest
  when: inventory_hostname in groups["prez"]

  vars_files:
    - vars/main.yml

- name: stop service
  service:
    name:
      - "{{ serveur_http }}"
      - "{{ sereur_app }}"
      - "{{ dbserver }}"
    state: stopped
  when: inventory_hostname in groups["prez"]